version: 0.2

phases:
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket layer-codepipeline-test-bucket --output-template-file outputtemplate.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml