version: 0.2

phases:
  build:
    commands:
      - export BUCKET=layer-codepipeline-test-bucket
      - aws cloudformation package --template-file layer-test-pipeline/template.yaml --s3-bucket $BUCKET --output-template-file layer-test-pipeline/outputtemplate.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml