AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello yoppy layer
Resources:
  HelloYoppytest1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.lambda_handler
      Runtime: python3.6
      FunctionName: HelloLayer
      CodeUri: hello.py
      Layers: 
        - !Ref LambdaLayer
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties: 
      CompatibleRuntimes: 
        - python3.6
        - python3.7
        - python3.8
      ContentUri: pandas/
      LayerName: tama-layer